alias dco='docker-compose'
alias dphp='docker-compose exec -u www-data app php'
alias dbash='docker-compose exec app bash'
alias dart='docker-compose exec -u www-data app php artisan'
alias dtinker='docker-compose exec -u www-data  app php artisan tinker'
alias dphpunit='docker-compose exec app vendor/bin/phpunit --stop-on-failure'
alias dcomposer='docker-compose exec -u www-data app composer'
